WHENEVER SQLERROR EXIT SQL.SQLCODE
SET DEFINE OFF

CREATE TABLE lab_metrics_1m (
 sample_time VARCHAR2(16), phase VARCHAR2(2), instance_id NUMBER, pdb_name VARCHAR2(30), service_name VARCHAR2(64),
 cpu_cores NUMBER, aas NUMBER, db_cpu_aas NUMBER, wait_aas NUMBER, host_cpu_pct NUMBER, os_run_queue NUMBER,
 top_wait VARCHAR2(64), physical_reads_blocks_s NUMBER, single_block_ms NUMBER, temp_io_ms NUMBER,
 pga_cache_hit_pct NUMBER, workarea_onepass_s NUMBER, workarea_multipass_s NUMBER, temp_gb_h NUMBER,
 buffer_hit_pct NUMBER, logical_reads_blocks_s NUMBER, hard_parses_s NUMBER, soft_parse_pct NUMBER,
 redo_mb_s NUMBER, user_commits_s NUMBER, log_file_sync_ms NUMBER, log_file_parallel_write_ms NUMBER,
 batch_rows_s NUMBER, merge_dbtime_pct NUMBER, literal_group_dbtime_pct NUMBER, other_dbtime_pct NUMBER,
 CONSTRAINT lab_metrics_pk PRIMARY KEY(sample_time, instance_id)
);
CREATE TABLE lab_ash_1m (
 sample_time VARCHAR2(16), phase VARCHAR2(2), instance_id NUMBER, pdb_name VARCHAR2(30), service_name VARCHAR2(64),
 sql_id VARCHAR2(13), force_matching_signature VARCHAR2(20), sql_label VARCHAR2(40), module VARCHAR2(48), action VARCHAR2(48),
 plan_hash_value VARCHAR2(20), session_state VARCHAR2(8), event VARCHAR2(64), wait_class VARCHAR2(32), sample_count NUMBER
);
CREATE INDEX lab_ash_i1 ON lab_ash_1m(sample_time, sql_id);
CREATE INDEX lab_ash_i2 ON lab_ash_1m(force_matching_signature, phase);
CREATE TABLE lab_top_sql (
 phase VARCHAR2(2), sql_id VARCHAR2(13), force_matching_signature VARCHAR2(20), sql_label VARCHAR2(40),
 module VARCHAR2(48), action VARCHAR2(48), plan_hash_value VARCHAR2(20), db_time_s NUMBER, db_time_pct NUMBER,
 cpu_time_s NUMBER, executions NUMBER, parse_calls NUMBER, buffer_gets NUMBER, disk_reads NUMBER,
 rows_processed NUMBER, temp_mb NUMBER
);
CREATE TABLE lab_awr_events (
 phase VARCHAR2(2), event VARCHAR2(64), wait_class VARCHAR2(32), time_s NUMBER, aas NUMBER,
 pct_db_time NUMBER, waits NUMBER, avg_wait_ms NUMBER
);
CREATE TABLE lab_run_control (
 run_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, started_at TIMESTAMP DEFAULT SYSTIMESTAMP,
 mode_name VARCHAR2(20), phase VARCHAR2(2), concurrency NUMBER, commit_batch NUMBER, status VARCHAR2(20), note VARCHAR2(200)
);
PROMPT Snapshot schema created.
